# When a tag is pushed, build packages and upload to PyPI

name: pypi upload

# Trigger when tags are pushed
on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build-and-upload:
    name: Upload packages to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies and build packages
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install build
          python -m build
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
