# Test example scripts

name: test examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow this workflow to be run manually from the Actions tab
  workflow_dispatch:


jobs:
  build-and-upload:
    name: Upload packages to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies and build packages
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run example test
        run: |
          ${GITHUB_WORKSPACE}/examples/scriptcheck.sh -e
